# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageRepo: web
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
  
    - task: Docker@2
      inputs:
          containerRegistry: 'My-ACR'
          repository: '$(imageRepo)'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Website/Dockerfile'
          tags: |
            $(tag)
            latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/Kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  variables: 
      walesecret: k8sexamplesearchauth
  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure Kubernetes
    environment: 'k8sdeployment.default'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy: 
          
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            inputs:
              action: 'createSecret'
              namespace: 'default'
              secretType: 'dockerRegistry'
              secretName: '$(walesecret)'
              dockerRegistryEndpoint: 'My-ACR'

          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              namespace: 'default'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment.yaml
                $(Pipeline.Workspace)/manifests/service.yaml
          
          
      
    



      