# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  imageRepo: web
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
  
    - task: Docker@2
      inputs:
          containerRegistry: 'My-ACR'
          repository: '$(imageRepo)'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/Website/Dockerfile'
          tags: |
            $(tag)
            latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/Kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  variables: 
      myacrsecret: my-aksCluster2022auth
  jobs:
  - job: Deploy
    displayName: Deploy to Azure Kubernetes
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifests'
    - task: KubernetesManifest@0
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: 'my-aksCluster2022'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: 'my-aksCluster2022auth'
        dockerRegistryEndpoint: 'My-ACR'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'my-aksCluster2022'
        namespace: 'default'
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yaml
          $(Pipeline.Workspace)/manifests/service.yaml
    
    
      
    



      