apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-deployment
  labels:
    app: static-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-website
  template:
    metadata:
      labels:
        app: static-website
    spec:
      containers:
      - name: web
        image: iacaksws1demo01acr.azurecr.io/web
        ports:
        - containerPort: 80
